---
title: Chingiz Huseynzade
email: chingiz.h[at]gmail[dot]com
description: |
  Student, Developer, Gamer, Tech Enthusiast
baseurl: ''
url: ''
twitter_username: hchingiz
github_username: Chingiz
disqus: chingizh
comments: false
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-admin
exclude:
- Gemfile
- Gemfile.lock
