---
title: Chingiz Huseynzade
email: chingiz.h[at]gmail[dot]com
description: |
  Student, Developer, Gamer, Tech Enthusiast
baseurl: ''
url: ''
twitter_username: hchingiz
github_username: Chingiz
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
